// // throw 'minha Exececao';
// // throw true;
// // throw 42;

// try {
//     criticalCode()
    
//   } catch (error) {
//     console.log(`[Erro]`);
//     console.log(error.message);
    
//   } finally {
  
//   }
  
  
//   try {
//     criticalCode()
    
//   } catch (e) {
//     console.log(`[Erro]`);
//     console.log(e.message);
    
//   } finally {
//     console.log(`Aqui sempre será executado ...`);
  
//   }


// try {
//     criticalCode()
    
//   } catch (error) {
//     console.log(`[Erro]`);
//     console.log(error.message);
    
//   } finally {
  
//   }
  
  
//   try {
//     criticalCode()
    
//   } catch (e) {
//     console.log(`[Erro]`);
//     console.log(e.message);
    
//   } finally {
//     console.log(`Aqui sempre será executado ...`);
  
//   }


  try {
    const divisor = 0;
    const resultado = 10; 
    console.log(`O resultado é; ${resultado}`);
    
  } catch (error) {
    console.error("Erro:", error.message);
  }
    
//   } finally {
//     console.log(`Aqui sempre será executado ...`);
  
//   }